package com.springboot.hibernateConnection.controller;

import java.util.ArrayList;
import java.util.List;

import org.apache.catalina.connector.Response;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.springboot.hibernateConnection.entity.WorkSpace;
import com.springboot.hibernateConnection.repository.WorkSpaceRepository;

@RequestMapping("/workspace")
@RestController
public class WorkSpaceController {
//

	@Autowired // This means to get the bean called workSpaceRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private WorkSpaceRepository workSpaceRepository;
	
	@CrossOrigin  // to ignore cors policy
	@GetMapping("/myWorkspace")
	public WorkSpace printHello(@RequestParam(value ="name", defaultValue = "New workspace") String wsName, @RequestParam(value = "des",
	defaultValue = "This is your first work space") String description) {
		System.out.println("/hello is requested: name="+wsName);
		return new WorkSpace(wsName, description);
	}
	
	@CrossOrigin  // to ignore cors policy
	@GetMapping("/addWorkspace")
	public String addWorkspace(@RequestParam(value ="name") String wsName, @RequestParam(value = "des") String description) {
		System.out.println("/hello is requested: name="+wsName);
		WorkSpace workspace = new WorkSpace(wsName, description);
		workSpaceRepository.save(workspace);
		return "sucess";
	}
	
	@CrossOrigin  // to ignore cors policy
	@GetMapping("/getWorkspace")
	public String getAllWS() {
//	    workSpaceRepository.findAll();
//	    for(int i=0;i<students.size();i++) {
//	    	System.out.println("Workspace: name-" + students.get(i).getName() + "; description-"+students.get(i).getDescription());
//	    }
	    return "see at console";
	}
	
} 
